# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
orbs:
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@2.1.0
  s3-cli: circleci/aws-s3@3.0.0
  ebs-cli: circleci/aws-elastic-beanstalk@2.0.1
# Define a job to be invoked later in a workflow.
jobs:
  deploy-app:
    # Specify the execution environment.
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    steps:
      - node/install
      - aws-cli/setup
      - checkout
      # - run:
      #     name: Install Front-End
      #     command: |
      #       npm run frontend:install
      # - run:
      #     name: Install Back-End
      #     command: |
      #       npm run backend:install
      # - run:
      #     name: Build Back-End
      #     command: |
      #       npm run backend:build
      # - run:
      #     name: Build Front-End
      #     command: |
      #       npm run frontend:build
      - run:
          name: Deploy Back-End
          command: |
            npm run backend:deploy
      # - run:
      #     name: Deploy Front-End
      #     command: |
      #       npm run frontend:deploy
      - run:
          name: "Done"
          command: echo "Job Done"

# Invoke jobs via workflows
workflows:
  project-workflow:
    jobs:
      - deploy-app
